### ISSUE TITLE
[제안] 공지채널 설정기능

### ISSUE THREAD

**Issue by samsunghappytree123** [samsunghappytree123/Sisby#3]
- 기능 이름을 말해주세요!
> 공지채널 설정기능

- 어떤 기능인가요?
> 공지채널 설정하여 그 채널에 공지가 가는 기능

- 어떤 효과가 발생하나요?
> 공지채널에 불평이 없을것이다.

- Sisby 개발자가 추가해야하나요?
> 추가할꺼

- [x] 활용성이 있나요?
- [x] 중복된 이슈가 없나요?

**Comment by kiki7000** [comment]
님
셀프 이슈는 필요 없음;;
차라리 프로젝트 쓰삼

**Comment by comjun04** [comment]
> 님
> 셀프 이슈는 필요 없음;;
> 차라리 프로젝트 쓰삼

@kiki7000 혹은 이슈랑 프로젝트랑 연동해서 사용할 수도 있어요

**Comment by samsunghappytree123** [comment]
@comjun04 감사한데 솔직하게 말하서 ~~프로젝트가 뭔지 몰라요~~

**Comment by kiki7000** [comment]
아아
